---
services:
  qdrant:
    image: qdrant/qdrant:latest
    restart: always
    container_name: qdrant
    ports:
      - 6333:6333
      - 6334:6334
    expose:
      - 6333
      - 6334
      - 6335
    configs:
      - source: qdrant_config
        target: /qdrant/config/production.yaml
    volumes:
      - ./qdrant_data:/qdrant/storage

configs:
  qdrant_config:
    content: |
      log_level: INFO

CONTEXT:
- [Retrieved Chunk 1]: "RAG combines retrieval with language models..."
- [Retrieved Chunk 2]: "Vector search uses embeddings to find semantic matches..."

INSTRUCTION: Answer concisely using only the context above.

QUESTION: What is RAG?